server:
  port: 7000
spring:
  mail:
    host: smtp.gmail.com
    password: <password>
    username: <email.address>
    port: 587
    sender: <email.address>
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    test-connection: true
