server:
  port: 7000
host:
  port:
    tls: 587
    ssl: 465
spring:
  mail:
    host: smtp.gmail.com
    username: <email-address>
    password: <password>
    port: ${host.port.tls}
    sender: <reply-to.email.address>
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: ${host.port.ssl}
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
